name: Build .NET Project on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # 在 Windows 上运行

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # 获取代码仓库

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1  # 配置 MSBuild 环境

    - name: Install Visual Studio Build Tools
      run: |
        choco install visualstudio2019buildtools --params "--add Microsoft.VisualStudio.Workload.NativeDesktop --includeRecommended --quiet"
        
    - name: Restore NuGet packages
      run: nuget restore qiapiao.sln  # 恢复依赖包，确保依赖已准备好

    - name: Build solution
      run: msbuild qiapiao.sln /p:Configuration=Release /p:Platform=x64

    - name: List files in bin\Release
      run: |
        Get-ChildItem -Path bin\Release -Recurse -Name  # 列出所有生成的文件，确保 DLL 存在

    - name: Publish DLL
      run: |
        mkdir output
        copy "bin\Release\x64\irml.dll" output/  # 根据实际路径复制 DLL

    - name: Upload DLL as artifact
      uses: actions/upload-artifact@v3
      with:
        name: YourProject-DLL
        path: output/irml.dll  # 上传生成的 DLL 文件
