name: Build C++ DLL with Visual Studio

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # 使用最新的 Windows 环境

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # 获取代码

    - name: Set up Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v1  # 设置 MSBuild 环境

    - name: Install Visual Studio Build Tools
      run: | 
        choco install visualstudio2022buildtools --params "--add Microsoft.VisualStudio.Workload.NativeDesktop --includeRecommended --quiet"

    - name: Restore NuGet packages
      run: nuget restore qiapiao.sln  # 恢复 NuGet 包（如果有的话）

    - name: Build solution
      run: |
        msbuild qiapiao.sln /p:Configuration=Release /p:Platform=x64  # 编译 Release 配置，指定 x64 平台

    - name: List generated files
      run: |
        Get-ChildItem -Path dll\Releasephysx27_64 -Recurse -Name  # 列出编译生成的文件，检查 DLL 是否存在

    - name: Publish DLL
      run: |
        mkdir output
        copy "dll\Releasephysx27_64\irml.dll" output/  # 根据实际路径复制 DLL 文件

    - name: Upload DLL as artifact
      uses: actions/upload-artifact@v3
      with:
        name: YourProject-DLL
        path: output/irml.dll  # 上传生成的 DLL 文件
